---

- name: Install packages
  include_tasks: install.yml

- name: Check if system have puppet facter installed
  ansible.builtin.stat:
    path: /opt/puppetlabs/bin/facter
  register: facter_installed

- name: Define facter facts
  include_tasks: facter.yml
  when: facter_installed.stat.exists

- name: "Check if Puppet managed node"
  ansible.builtin.command:
    cmd: grep -i Puppet /etc/snmp/snmpd.conf
  check_mode: false
  register: snmpd_puppet_managed
  changed_when: snmpd_puppet_managed.rc == 0
  failed_when: snmpd_puppet_managed.rc == 128

- name: Template snmp configuration
  template:
    src: templates/snmpd.conf.j2
    dest: /etc/snmp/snmpd.conf
    backup: true
  notify:
    - restart snmpd
  when: not snmpd_puppet_managed.changed
